
package web.tpsoap.wd.client;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.0.2
 * Generated source version: 2.2
 * 
 */
@WebService(name = "HotelWebService", targetNamespace = "http://wd.tpsoap.web/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface HotelWebService {


    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg5
     * @param arg4
     * @param arg1
     * @param arg0
     * @param arg7
     * @param arg6
     * @param arg8
     */
    @WebMethod
    @RequestWrapper(localName = "makeReservation", targetNamespace = "http://wd.tpsoap.web/", className = "web.tpsoap.wd.client.MakeReservation")
    @ResponseWrapper(localName = "makeReservationResponse", targetNamespace = "http://wd.tpsoap.web/", className = "web.tpsoap.wd.client.MakeReservationResponse")
    @Action(input = "http://wd.tpsoap.web/HotelWebService/makeReservationRequest", output = "http://wd.tpsoap.web/HotelWebService/makeReservationResponse")
    public void makeReservation(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        String arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        Long arg4,
        @WebParam(name = "arg5", targetNamespace = "")
        Long arg5,
        @WebParam(name = "arg6", targetNamespace = "")
        Long arg6,
        @WebParam(name = "arg7", targetNamespace = "")
        int arg7,
        @WebParam(name = "arg8", targetNamespace = "")
        int arg8);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "isPartenaire", targetNamespace = "http://wd.tpsoap.web/", className = "web.tpsoap.wd.client.IsPartenaire")
    @ResponseWrapper(localName = "isPartenaireResponse", targetNamespace = "http://wd.tpsoap.web/", className = "web.tpsoap.wd.client.IsPartenaireResponse")
    @Action(input = "http://wd.tpsoap.web/HotelWebService/isPartenaireRequest", output = "http://wd.tpsoap.web/HotelWebService/isPartenaireResponse")
    public boolean isPartenaire(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns web.tpsoap.wd.client.Agence
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAgence", targetNamespace = "http://wd.tpsoap.web/", className = "web.tpsoap.wd.client.GetAgence")
    @ResponseWrapper(localName = "getAgenceResponse", targetNamespace = "http://wd.tpsoap.web/", className = "web.tpsoap.wd.client.GetAgenceResponse")
    @Action(input = "http://wd.tpsoap.web/HotelWebService/getAgenceRequest", output = "http://wd.tpsoap.web/HotelWebService/getAgenceResponse")
    public Agence getAgence(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.util.List<web.tpsoap.wd.client.Chambre>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "searchChambre", targetNamespace = "http://wd.tpsoap.web/", className = "web.tpsoap.wd.client.SearchChambre")
    @ResponseWrapper(localName = "searchChambreResponse", targetNamespace = "http://wd.tpsoap.web/", className = "web.tpsoap.wd.client.SearchChambreResponse")
    @Action(input = "http://wd.tpsoap.web/HotelWebService/searchChambreRequest", output = "http://wd.tpsoap.web/HotelWebService/searchChambreResponse")
    public List<Chambre> searchChambre(
        @WebParam(name = "arg0", targetNamespace = "")
        Long arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        Long arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        int arg2);

}
